/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.1 (UNKNOWN)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdemCursos { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idcurso?: number;
    nombre?: string;
    descripcion?: string;
    descripcion2?: string;
    imagen?: string;
    costo?: number;
    moneda?: string;
    /**
     * Note: This is a Foreign Key to `item_tipocursos.idtipocurso`.<fk table='item_tipocursos' column='idtipocurso'/>
     */
    idtipocurso?: number;
    fechahorainicio?: string;
    fechahorafin?: string;
    lugar?: string;
    fecharegistro?: string;
    /**
     * Note: This is a Foreign Key to `idem_categorias.idcategoria`.<fk table='idem_categorias' column='idcategoria'/>
     */
    idcategoria?: number;
    urlexternocurso?: string;
    costodescripcion?: string;
}
