/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * el campo permiso: 0 - Solo ver  (R) 1- Ver y modificar  (RU) 2- ver,modificar y crear  (CRU) 3- ver,modificar crear y eliminar (CRUD)  
 */
export interface IdemPermisos { 
    /**
     * Note: This is a Primary Key.<pk/> This is a Foreign Key to `idem_apartados.idapartado`.<fk table='idem_apartados' column='idapartado'/>
     */
    idapartado: number;
    /**
     * Note: This is a Primary Key.<pk/> This is a Foreign Key to `idem_cargos.idcargo`.<fk table='idem_cargos' column='idcargo'/>
     */
    idcargo: number;
    permiso: number;
    fecharegistro?: string;
}
