/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdemCategorias { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idcategoria: number;
    /**
     * cursod e negocios, de tecnologia etc
     */
    nombre?: string;
    idestado?: number;
}
