/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdemUsuarios { 
    /**
     * Note: This is a Primary Key.<pk/> This is a Foreign Key to `idem_personas.dni`.<fk table='idem_personas' column='dni'/>
     */
    dni: string;
    idcargo?: number;
    email?: string;
    password?: string;
    /**
     * Note: This is a Foreign Key to `idem_cargos.idcargo`.<fk table='idem_cargos' column='idcargo'/>
     */
    idestado?: number;
    fecharegistro?: string;
}
