/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * idem_rel_cursos_alumnos
 */
export interface IdemMatriculas { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idmatricula: number;
    /**
     * Note: This is a Foreign Key to `idem_alumnos.dni`.<fk table='idem_alumnos' column='dni'/>
     */
    dni: string;
    /**
     * Note: This is a Foreign Key to `idem_cursos.idcurso`.<fk table='idem_cursos' column='idcurso'/>
     */
    idcurso: number;
    fecharegistro?: string;
}
