/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdemRelCursosModulos { 
    /**
     * Note: This is a Primary Key.<pk/> This is a Foreign Key to `idem_cursos.idcurso`.<fk table='idem_cursos' column='idcurso'/>
     */
    idcurso: number;
    /**
     * Note: This is a Primary Key.<pk/> This is a Foreign Key to `idem_modulos.idmodulo`.<fk table='idem_modulos' column='idmodulo'/>
     */
    idmodulo: number;
    fechahoraInicio?: string;
    fechahoraFin?: string;
    lugar?: string;
    fecharegistro?: string;
}
