/**
 * PostgREST API
 * standard public schema
 *
 * OpenAPI spec version: 7.0.0 (2b61a63)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface IdemModulos { 
    /**
     * Note: This is a Primary Key.<pk/>
     */
    idmodulo: number;
    nombre: string;
    /**
     * Note: This is a Foreign Key to `idem_docentes.dni`.<fk table='idem_docentes' column='dni'/>
     */
    dniProfesor?: string;
    imagen?: string;
    video?: string;
    descripcion?: string;
    /**
     * Note: This is a Foreign Key to `idem_estados.ideestado`.<fk table='idem_estados' column='ideestado'/>
     */
    idestado?: number;
    fecharegistro: string;
}
