export * from './idemAlumnos.service';
import { IdemAlumnosService } from './idemAlumnos.service';
export * from './idemApartados.service';
import { IdemApartadosService } from './idemApartados.service';
export * from './idemCargos.service';
import { IdemCargosService } from './idemCargos.service';
export * from './idemCategorias.service';
import { IdemCategoriasService } from './idemCategorias.service';
export * from './idemCursos.service';
import { IdemCursosService } from './idemCursos.service';
export * from './idemDocentes.service';
import { IdemDocentesService } from './idemDocentes.service';
export * from './idemEstados.service';
import { IdemEstadosService } from './idemEstados.service';
export * from './idemMatriculas.service';
import { IdemMatriculasService } from './idemMatriculas.service';
export * from './idemModulos.service';
import { IdemModulosService } from './idemModulos.service';
export * from './idemModulosComentarios.service';
import { IdemModulosComentariosService } from './idemModulosComentarios.service';
export * from './idemPagos.service';
import { IdemPagosService } from './idemPagos.service';
export * from './idemPermisos.service';
import { IdemPermisosService } from './idemPermisos.service';
export * from './idemPersonas.service';
import { IdemPersonasService } from './idemPersonas.service';
export * from './idemRelCursosModulos.service';
import { IdemRelCursosModulosService } from './idemRelCursosModulos.service';
export * from './idemUsuarios.service';
import { IdemUsuariosService } from './idemUsuarios.service';
export * from './introspection.service';
import { IntrospectionService } from './introspection.service';
export * from './itemTipocursos.service';
import { ItemTipocursosService } from './itemTipocursos.service';
export const APIS = [IdemAlumnosService, IdemApartadosService, IdemCargosService, IdemCategoriasService, IdemCursosService, IdemDocentesService, IdemEstadosService, IdemMatriculasService, IdemModulosService, IdemModulosComentariosService, IdemPagosService, IdemPermisosService, IdemPersonasService, IdemRelCursosModulosService, IdemUsuariosService, IntrospectionService, ItemTipocursosService];
